# Week 48

## Activities

### Activity 8.6

Determine the eigenvectors for $0$ and $12$. Check your answers: verify that $Av = \lambda v$ for each eigenvalue and one corresponding eigenvector.

$$A = \begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}$$

$$|A-\lambda I| = (4-\lambda)\lambda(\lambda-12)$$

First calculate the eigenvectors for the eigenvalue of $0$:

$$|A-0I| = A$$

$$\begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}-0\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

$$\Updownarrow$$

$$\begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}-\begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix} = \begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}$$

Put matrix $A$ in REF

$$\begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}$$

$$\xrightarrow{\frac{1}{4}R_1}R_1$$

$$\begin{bmatrix} 1 & 0 & 1 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}$$

$$\xrightarrow{R_3-4R_1}R_3$$

$$\begin{bmatrix} 1 & 0 & 1 \\ 0 & 4 & 4 \\ 0 & 4 & 4 \end{bmatrix}$$

$$\xrightarrow{\frac{1}{4}R_2}R_2$$

$$\begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 0 & 4 & 4 \end{bmatrix}$$

$$\xrightarrow{R_3-4R_2}R_3$$

$$\begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 0 & 0 & 0 \end{bmatrix}$$

$$x = t \begin{bmatrix} -1 \\ -1 \\ 1 \end{bmatrix}, \space t \in \mathbb{R}$$

Then we calculate the eigenvector for the eigenvalue of 12:

$$|A-12I| = A$$

$$\begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}-12\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

$$\Updownarrow$$

$$\begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}-\begin{bmatrix} 12 & 0 & 0 \\ 0 & 12 & 0 \\ 0 & 0 & 12 \end{bmatrix} = \begin{bmatrix} 4 & 0 & 4 \\ 0 & 4 & 4 \\ 4 & 4 & 8 \end{bmatrix}$$

Put matrix $A$ in REF

$$\begin{bmatrix} -8 & 0 & 4 \\ 0 & -8 & 4 \\ 4 & 4 & -4 \end{bmatrix}$$

$$\xrightarrow{-\frac{1}{8}R_1}R_1$$

$$\begin{bmatrix} 1 & 0 & -\frac{1}{2} \\ 0 & -8 & 4 \\ 4 & 4 & -4 \end{bmatrix}$$

$$\xrightarrow{R_3-4R_1}R_3$$

$$\begin{bmatrix} 1 & 0 & -\frac{1}{2} \\ 0 & -8 & 4 \\ 0 & 4 & -2 \end{bmatrix}$$

$$\xrightarrow{-\frac{1}{8}R_2}R_2$$

$$\begin{bmatrix} 1 & 0 & -\frac{1}{2} \\ 0 & 1 & -\frac{1}{2} \\ 0 & 4 & -2 \end{bmatrix}$$

$$\xrightarrow{R_3-4R_2}R_3$$

$$\begin{bmatrix} 1 & 0 & -\frac{1}{2} \\ 0 & 1 & -\frac{1}{2} \\ 0 & 0 & 0 \end{bmatrix}$$

$$x = t \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}, \space t \in \mathbb{R}$$

### Activity 8.8

$$-(\lambda+1)(\lambda^2+b\lambda + 2)$$

$$-(\lambda^2+b\lambda^2)$$

$$-\lambda^2 - b\lambda^2 = -4\lambda^2$$

$$b=3$$

### Activity 8.19 

$$A = \begin{bmatrix} 7 & -15 \\ 2 & -4 \end{bmatrix}, \space \space \space P = \begin{bmatrix} 5 & 3 \\ 2 & 1 \end{bmatrix}$$

$$P^{-1}AP=D=\begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix}$$

$$AP = \begin{bmatrix} 7 & -15 \\ 2 & -4 \end{bmatrix} \begin{bmatrix} 5 & 3 \\ 2 & 1 \end{bmatrix} =\begin{bmatrix} 5 & 6 \\ 2 & 2 \end{bmatrix} $$

$$P^{-1} = -1 \begin{bmatrix} 1 & -3 \\ -2 & 5 \end{bmatrix} = \begin{bmatrix} -1 & 3 \\ 2 & -5 \end{bmatrix}$$

$$P^{-1}AP = \begin{bmatrix} -1 & 3 \\ 2 & -5 \end{bmatrix}\begin{bmatrix} 5 & 6 \\ 2 & 2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix}$$

## Exercises 

### Exercise 8.5

$$A = \begin{bmatrix} 6 & 13 & -8 \\ 2 & 5 & -2 \\ 7 & 17 & -9 \end{bmatrix}, \space \space \space v = \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}$$

$$\begin{bmatrix} 6 & 13 & -8 \\ 2 & 5 & -2 \\ 7 & 17 & -9 \end{bmatrix}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} -2 \\ 0 \\ -2 \end{bmatrix}$$

Eigenvalue is $-2$.

The transformation shows us that there is an eigenvalue of $1$ therefor we can write:

$$A-I = \begin{bmatrix} 6 & 13 & -8 \\ 2 & 5 & -2 \\ 7 & 17 & -9 \end{bmatrix}-\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} = \begin{bmatrix} 5 & 13 & -8 \\ 2 & 4 & -2 \\ 7 & 17 & -10 \end{bmatrix}$$

$$\xrightarrow{R_1 \Leftrightarrow R_2}R_1$$
$$\xrightarrow{\frac{1}{2}R_1}R_1$$


$$\begin{bmatrix} 1 & 2 & -1 \\ 5 & 13 & -8 \\ 7 & 17 & -10 \end{bmatrix}$$

$$\xrightarrow{R_2-5R_1}R_2$$

$$\begin{bmatrix} 1 & 2 & -1 \\ 0 & 3 & -3 \\ 7 & 17 & -10 \end{bmatrix}$$

$$\xrightarrow{R_3-7R_1}R_3$$

$$\begin{bmatrix} 1 & 2 & -1 \\ 0 & 3 & -3 \\ 0 & 3 & -3 \end{bmatrix}$$

$$\xrightarrow{\frac{1}{3}R_2}R_2$$

$$\begin{bmatrix} 1 & 2 & -1 \\ 0 & 1 & -1 \\ 0 & 3 & -3 \end{bmatrix}$$

$$\xrightarrow{R_3-3R_2}R_3$$

$$\begin{bmatrix} 1 & 2 & -1 \\ 0 & 1 & -1 \\ 0 & 0 & 0 \end{bmatrix}$$

$$\xrightarrow{R_1-2R_2}R_1$$

$$\begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & -1 \\ 0 & 0 & 0 \end{bmatrix}$$

$$x = t \begin{bmatrix} -1 \\ 1 \\ 1 \end{bmatrix}, \space t \in \mathbb{R}$$

## Problems 

### Problem 8.1

Determine which, if any, of the following vectors are eigenvectors for the given matrix $A$:

$$x= \begin{bmatrix} 1 \\ -1 \\ 3 \end{bmatrix}, \space \space \space y= \begin{bmatrix} 1 \\ 5 \\ 3 \end{bmatrix}, \space \space \space z= \begin{bmatrix} 5 \\ 0 \\ 1 \end{bmatrix}; \space \space \space A= \begin{bmatrix} 1 & 1 & 0 \\ 1 & 4 & 3 \\ 0 & 3 & 1 \end{bmatrix}.$$

$$Ax = \begin{bmatrix} 1 & 1 & 0 \\ 1 & 4 & 3 \\ 0 & 3 & 1 \end{bmatrix}\begin{bmatrix} 1 \\ -1 \\ 3 \end{bmatrix} = \begin{bmatrix} 0 \\ 6 \\ 0 \end{bmatrix}$$

$$Ay = \begin{bmatrix} 1 & 1 & 0 \\ 1 & 4 & 3 \\ 0 & 3 & 1 \end{bmatrix}\begin{bmatrix} 1 \\ 5 \\ 3 \end{bmatrix} = \begin{bmatrix} 6 \\ 30 \\ 18 \end{bmatrix}$$

$$Az = \begin{bmatrix} 1 & 1 & 0 \\ 1 & 4 & 3 \\ 0 & 3 & 1 \end{bmatrix}\begin{bmatrix} 5 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} 5 \\ 8 \\ 1 \end{bmatrix}$$

In [52]:
A = np.matrix([[1, 1, 0], [1 ,4, 3], [0, 3, 1]])
x = np.transpose(np.matrix([[1, -1, 3]]))
y = np.transpose(np.matrix([[1, 5, 3]]))
z = np.transpose(np.matrix([[5, 0, 1]]))

print(A*x)
print(A*y)
print(A*z)

[[0]
 [6]
 [0]]
[[ 6]
 [30]
 [18]]
[[5]
 [8]
 [1]]
